server:
#  port: 10000
  port: 33333

spring:
  main:
    allow-bean-definition-overriding: true

  application:
    name: boardproject

  datasource:
    url: jdbc:mysql://14.35.173.14:26711/boardproject
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: passw0rd
  sql:
    init:
      mode: never

  #  mail:
  #    host: smtp.gmail.com
  #    port: 587
  #    username:
  #    password:
  #    properties:
  #      mail:
  #        smtp:
  #          auth: true
  #          starttls:
  #            enable: true

  thymeleaf:
    cache: false

#  servlet:
#    multipart:
#      enabled: true
#      location:
#      max-file-size: 50MB
#      max-request-size: 50MB
#
#uploadPath:
#tempUploadPath:

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true